import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import AdminAccount from '@/components/AdminAccount';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {children} */}
        <AdminAccount />
      </body>
    </html>
  );
}
